### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by pongopal** [gvalvano/sdnet#2]
Progress: [==> Traceback (most recent call last):
Traceback (most recent call last):
File "train.py", line 34, in
model.train(n_epochs=N_EPOCHS)
File "/media/leon/extra/SemiSSET/code/model.py", line 633, in train
t_step = self.train_one_epoch(sess, iterator_init_list, writer, t_step, caller, seed)
File "/media/leon/extra/SemiSSET/code/model.py", line 430, in train_one_epoch
sup_loss, unsup_loss = self._train_all_op(sess, writer, step)
File "/media/leon/extra/SemiSSET/code/model.py", line 396, in _train_all_op
feed_dict={self.is_training: True})
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by gvalvano** [comment]
My bad! After polishing up the code I removed one line. Bug fixed :)

**Comment by gvalvano** [comment]
@pongopal Let me know if you have other problems, otherwise, I will close the issue :-)

If you find the code useful for your experiments, please consider citing me as specified in the READ_ME. Thank you!
